### ISSUE TITLE
Doesn't work with macOS Sierra.

### ISSUE THREAD

**Issue by saumiko** [torifat/iAvro#20]
I have updated my mac to the latest release. iAvro stopped working in it. This issue needs to be fixed.

**Comment by torifat** [comment]
@saumiko Hi, Thanks for reporting. We are aware of it and will release a new version as soon as possible.

**Comment by mugli** [comment]
Updated installer is published here: https://www.omicronlab.com/iavro-download.html

**Comment by saumiko** [comment]
Thanks a lot. :)
