### ISSUE TITLE
Dictionary Suggestion Scroll doesn't work in macOS Mojave

### ISSUE THREAD

**Issue by ShawonAshraf** [torifat/iAvro#26]
The dictionary suggestion does pop up but can't scroll down and pick the desired suggestion using arrow keys.

**Comment by dongyuwei** [comment]
I run into the same bug on Mojave 10.14. Fixed it now, see https://github.com/dongyuwei/hallelujahIM. 
My code use `-(BOOL)handleEvent:(NSEvent*)event client:(id)sender;`, while iAvro use `- (BOOL)inputText:(NSString*)string client:(id)sender`. They both should work but apple engineers broken the old api.

**Comment by Zibonnn** [comment]
Facing the same problem. Please fix it. Thank you.

**Comment by Ataurr** [comment]
Same issue here as well

**Comment by fayazmiraz** [comment]
This should be labeled as a bug.
It became very difficult writing Bangla with Avro in Mojave.

**Comment by mugli** [comment]
@sarim already prepared a fix. I'll try to release a new version as soon as I can.

**Comment by mugli** [comment]
Updated iAvro 1.5 with macOS Mojave support released here: https://www.omicronlab.com/iavro-download.html
