### ISSUE TITLE
How can I switch to ANSI mode?

### ISSUE THREAD

**Issue by fayaz-dev** [torifat/iAvro#28]
Avro Windows version has **ANSI** mode, does the Mac version (iAvro) have ANSI mode too?
If so, then how can I switch to ANSI input mode (I'm on **macOS Mojave**)?

Some photo editor apps (like Affinity Photo) need ANSI input to show Bangla properly. For now, I manually convert the Unicode text to ANSI and then copy/paste the text (while an ANSI font is selected) for Apps like this to show proper Bangla text. It works, but it's really inconvenient!

**Comment by torifat** [comment]
Sorry, there isn't any ANSI mode, and we don't have any plan to add it either.

**Comment by MZI-Jibon** [comment]
@torifat 
Please try to add ANSI mode in Avro for Mac.
It will help many content creators nationwide.

**Comment by aOsmani1998** [comment]
Please bring ANSI to iAvro. I'm prepared to pay for it too. Please. It would be so helpful for me

**Comment by SNNafi** [comment]
@torifat , If you can give me some ideas on how to do it, I may give it a try within the next 2-3 months depending on free bandwidth.

**Comment by torifat** [comment]
There are legal implications for doing it, and we would like to avoid it.

**Comment by aOsmani1998** [comment]
> There are legal implications for doing it, and we would like to avoid it.

I'm a lawyer and our law chamber is one of the finest for IP (Intellectual Property) Laws. If you need I can help gliding through the legal proceedings.
