### ISSUE TITLE
Need support for custom keyboard layout.

### ISSUE THREAD

**Issue by sohojmanush** [torifat/iAvro#30]
Avro for windows has an option to add a custom layout. But, it seems like iAvro doesn't have that option to add a custom layout .avrolayout. Adding a custom layout option on iAvro will be much helpful for people who prefer a dedicated keyboard layout.

**Comment by torifat** [comment]
There are existing fixed keyboard layout builders for MacOS. So, we don't have plan to add support for it in the Mac version.
